# -- Override full name
fullnameOverride: ""
# -- Override name
nameOverride: ""

# -- Replica count
replicaCount: 1
image:
  # -- Image repository
  repository: ghcr.io/sap/cf-service-operator
  # -- Image tag (defauls to .Chart.AppVersion)
  tag: ""
  # -- Image pull policy
  pullPolicy: IfNotPresent
# -- Image pull secrets
imagePullSecrets: []
# -- Affinity settings
affinity: {}
# -- Topology spread constraints (if unspecified, default constraints for hostname and zone will be generated)
topologySpreadConstraints: []
# -- Default topology spread policy for hostname
defaultHostNameSpreadPolicy: ScheduleAnyway
# -- Default topology spread policy for zone
defaultZoneSpreadPolicy: ScheduleAnyway
# -- Node selector
nodeSelector: {}
# -- Tolerations
tolerations: []
# -- Priority class
priorityClassName: ""
# -- Pod security context
podSecurityContext: {}
# -- Additional pod annotations
podAnnotations: {}
# -- Additional pod labels
podLabels: {}
# -- Container security context
securityContext: {}
resources:
  limits:
    # -- Memory limit
    memory: 200Mi
    # -- CPU limit
    cpu: 0.1
  requests:
    # -- Memory request
    memory: 20Mi
    # -- CPU request
    cpu: 0.01

# -- Enable SAP binding metadata (per default, can be overridden by annotation service-operator.cf.cs.sap.com/with-sap-binding-metadata)
enableSapBindingMetadata: false
