{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.data }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .secretPath }}
        property: password
      secretKey: password
    - remoteRef:
        key: {{ .secretPath }}
        property: url
      secretKey: url
    - remoteRef:
        key: {{ .secretPath }}
        property: username
      secretKey: username
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    kind: {{ .secretStoreRef.kind }}
    name: {{ .secretStoreRef.name }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .name }}
{{- end }}
{{- end }}