---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-service-operator.fullname" . }}
  labels:
    {{- include "cf-service-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cf-service-operator.fullname" . }}
  labels:
    {{- include "cf-service-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cf-service-operator.fullname" . }}
  labels:
    {{- include "cf-service-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cf.cs.sap.com
  resources:
  - clusterspaces
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cf.cs.sap.com
  resources:
  - clusterspaces/finalizers
  verbs:
  - update
- apiGroups:
  - cf.cs.sap.com
  resources:
  - clusterspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cf.cs.sap.com
  resources:
  - servicebindings
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cf.cs.sap.com
  resources:
  - servicebindings/finalizers
  verbs:
  - update
- apiGroups:
  - cf.cs.sap.com
  resources:
  - servicebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cf.cs.sap.com
  resources:
  - serviceinstances
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cf.cs.sap.com
  resources:
  - serviceinstances/finalizers
  verbs:
  - update
- apiGroups:
  - cf.cs.sap.com
  resources:
  - serviceinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cf.cs.sap.com
  resources:
  - spaces
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cf.cs.sap.com
  resources:
  - spaces/finalizers
  verbs:
  - update
- apiGroups:
  - cf.cs.sap.com
  resources:
  - spaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cf-service-operator.fullname" . }}
  labels:
    {{- include "cf-service-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "cf-service-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cf-service-operator.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cf-service-operator.fullname" . }}
  labels:
    {{- include "cf-service-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "cf-service-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cf-service-operator.fullname" . }}
